name: muslim_app
description: Muslim App - Quran, Hadist, Sholat, Kiblat
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.1.0
  flutter_compass: ^0.8.0
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
